name: Autoupdate
on:
  schedule:
    - cron: '34 12 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download from S3
        run: |
          wget -O rl-read-only.template https://redlock-public.s3.amazonaws.com/cft/rl-read-only.template
          wget -O rl-read-and-write.template https://redlock-public.s3.amazonaws.com/cft/rl-read-and-write.template
          wget -O rl-storage-read-only.template https://redlock-public.s3.amazonaws.com/cft/rl-storage-read-only.template
          wget -O rl-storage-read-and-write.template https://redlock-public.s3.amazonaws.com/cft/rl-storage-read-and-write.template
      - uses: EndBug/add-and-commit@v8
        with:
          add: '*.template'
          author_name: 'Prisma Role Bot'
